### ISSUE TITLE
Add type checking and error handling

### ISSUE THREAD

**Issue by PavithraUmakanthan** [PavithraUmakanthan/ES6_fizzbuzz#6]

**Comment by stephanielingwood** [comment]
Now that you have unit tests working, it's time to add some more functionality to `fizzbuzz`. 

## Step 1: Write unit tests for 3 error cases
- Decide on three error cases for your fizzbuzz function, and how it should respond. For example, you might handle the case where `fizzbuzz` isn't passed a number. You might decide that if `fizzbuzz` is passed the value `one`, that it should return a string saying "Sorry, 'one' is not a number." 
- Write a test for each of these three error cases. When you're done, all three tests should run and fail (because you haven't written the code to handle errors yet). You should see the output for these tests in the console, just like your other unit tests.

## Step 2: Add type checking and error handling
- Add checks at the beginning of the `fizzbuzz` function that test for your different error cases, and send an appropriate response.
- When you're done with this, your tests should all pass.

## Step 3: Add error codes
Until now, your errors are returned as simply strings - e.g. "Sorry, 'one' is not a number". Now, you need to return error codes along with that string. 

### Step 3, Part 1: determine your error codes
- Create (in pseudocode) 3-4 different codes for different types of errors. Each of those codes should have a name (like typeError) and number (like, 400). You get to make up the codes and error types.

### Step 3, Part 2: test for error codes
- Change your test so that it expects to have an error object returned to it, vs. an error string. For example, it should expect to receive `{status: 400, message: "Sorry, 'one' is not a number"}`
- This means your existing test will need to compare against the error message, not just the value.
- Then, add three new tests (one for each error case) that test that the status code returned is what you expect. So, for my "one is not a number" case, I'd have two tests: one testing the message, and one testing the value of `status`.

### Step 3, part 3: Add an error code map
Now, you'll define the error codes possible in your application. Like your tests, you want them to be in their own file. If your application grew to include other files (like, a new game, FuzzBuzz explodes in popularity and you implement that as well), you'd want to re-use your error codes across files. 
- Create a `statusCodes.js` file. That file should export a single object: one that maps numerical codes to names. In another file, I should be able to, say, reference the statusCodes.typeError property, and have it return my number of choice.

### Step 3, part 4: Return error codes along with your error messages
In your `fizzbuzz` function, your error handling should now return an object, not a string. 
- That object should have two properties: `status` and `message`
- `status` should reference the appropriate property of the object exported by `statusCodes`
- `message` should be the existing error string
- When you're done with this step, all your tests should pass.

**Comment by PavithraUmakanthan** [comment]
Merged my changes to master. Closing the issue.
